// Commented by ChatGPT

using UnityEditor;
using UnityEngine;
using UnityEngine.InputSystem;

public class PlayerController : MonoBehaviour
{
    #region Input System Fields

    // This is the C# wrapper class generated by Unity's Input System
    // (usually created from your .inputactions file).
    private PlayerInputAction playerInput;

    // Movement input (WASD / left stick)
    private Vector2 moveInput;

    // Look input (mouse delta / right stick)
    private Vector2 lookInput;

    // Sprint input (button/trigger, depending on your binding)
    private float sprintInput;

    // We do NOT want to poll interact as a float each frame,
    // because holding the key would trigger every frame.
    // Instead, we use a "pressed this frame" flag that is set by an input event.
    private bool interactPressedThisFrame;

    #endregion

    #region Tunable Settings

    public float moveSpeed = 5f;               // Base walking speed
    public float sprintSpeed = 2f;             // Sprint multiplier (2 = twice as fast)
    public float interactDistance = 3f;        // How far the raycast can reach

    public float mouseSensitivity = 0.1f;      // Mouse look sensitivity (small numbers usually)
    public float controllerSensitivity = 120f; // Controller look sensitivity (bigger numbers usually)

    #endregion

    #region Health / Vitals

    // These are properties (get; private set;) so other scripts can read them,
    // but only THIS script can change them.
    public int playerHealth { get; private set; }
    public int gasMaskHealth { get; private set; }

    #endregion

    #region Internal State

    // Pitch is the up/down look angle (camera only)
    private float pitch;

    // Reference to the FPS camera
    private Camera playerCamera;

    #endregion

    #region Unity Lifecycle

    // Cache references and create the input wrapper
    void Awake()
    {
        // Create the input wrapper instance
        playerInput = new PlayerInputAction();

        // Find the camera under the player (common FPS setup)
        playerCamera = GetComponentInChildren<Camera>();

        // Cursor behavior for FPS: lock to center and hide it
        Cursor.lockState = CursorLockMode.Locked;
        Cursor.visible = false;

        // Optional: initialize health values here if you want starting values.
        // (Right now defaults to 0 unless you set them somewhere else.)
        // playerHealth = 100;
        // gasMaskHealth = 100;
    }

    // Enable action map and hook input events
    void OnEnable()
    {
        // Enable the "Player" action map so actions start sending values
        playerInput.Player.Enable();

        // IMPORTANT:
        // Subscribe to the Interact action event so it fires ONCE per press.
        // This avoids "held key = spam every frame".
        playerInput.Player.Interact.performed += OnInteractPerformed;
    }

    // Disable action map and unhook input events
    void OnDisable()
    {
        // Unsubscribe from events to prevent duplicate subscriptions / memory issues
        playerInput.Player.Interact.performed -= OnInteractPerformed;

        // Disable the map so we stop receiving inputs
        playerInput.Player.Disable();
    }

    // Read inputs and apply movement/look
    void Update()
    {
        // Movement vector: (x = left/right, y = forward/back)
        moveInput = playerInput.Player.Move.ReadValue<Vector2>();

        // Look vector: (x = yaw, y = pitch)
        lookInput = playerInput.Player.Look.ReadValue<Vector2>();

        // Sprint: often 0 or 1 (button), or 0..1 (trigger)
        sprintInput = playerInput.Player.Sprint.ReadValue<float>();

        // Apply movement and look every frame
        HandleMove();
        HandleLook();

        // Interact should only happen ONCE per press.
        // The input event sets interactPressedThisFrame = true,
        // then we consume it here and immediately reset it.
        if (interactPressedThisFrame)
        {
            interactPressedThisFrame = false;
            HandleInteract();
        }
    }

    #endregion

    #region Input Event Callbacks

    // This function is called by the Input System when the Interact action is performed.
    // For a Button action, "performed" typically occurs once per press.
    private void OnInteractPerformed(InputAction.CallbackContext context)
    {
        // Set a flag that Update will consume.
        // This guarantees "one interaction per press".
        interactPressedThisFrame = true;
    }

    #endregion

    #region Interaction

    // Handle Raycast for interacting
    void HandleInteract()
    {
        // Create a ray from the center of the camera view (crosshair position).
        // (0.5, 0.5) is the center in viewport coordinates.
        Ray ray = playerCamera.ViewportPointToRay(new Vector3(0.5f, 0.5f, 0f));

        // Fire the raycast. If it hits something within interactDistance, we get info in "hit".
        if (Physics.Raycast(ray, out RaycastHit hit, interactDistance))
        {
            // At this point, we KNOW the interact button was pressed (because Update only calls this then),
            // and we KNOW we hit something.

            // Next step is usually:
            // 1) check if the object is interactable
            // 2) call some method on it
            // For now, we're just printing what we hit.
            Debug.Log("Hit: " + hit.collider.name);
        }
        else
        {
            // Optional: if you want to know when you're pressing interact on nothing
            // Debug.Log("Interact pressed, but nothing was hit.");
        }
    }

    #endregion

    #region Movement

    // Move in local space (forward/back/left/right)
    void HandleMove()
    {
        // Convert 2D input into world movement:
        // - transform.right moves along the player's right direction
        // - transform.forward moves along the player's forward direction
        Vector3 move =
            (transform.right * moveInput.x) +
            (transform.forward * moveInput.y);

        // If sprint is pressed, speed is multiplied
        if (sprintInput > 0)
        {
            transform.position += move * (moveSpeed * sprintSpeed) * Time.deltaTime;
        }
        else
        {
            transform.position += move * moveSpeed * Time.deltaTime;
        }
    }

    #endregion

    #region Look / Camera Rotation

    // Yaw on player, pitch on camera
    void HandleLook()
    {
        // Detect if the last update came from a gamepad.
        // This helps choose different sensitivities and apply deltaTime correctly.
        bool usingGamepad = Gamepad.current != null && Gamepad.current.wasUpdatedThisFrame;

        // Choose sensitivity based on input device
        float sensitivity = usingGamepad ? controllerSensitivity : mouseSensitivity;

        // Horizontal look (turn left/right)
        float yaw = lookInput.x * sensitivity;

        // Vertical look (look up/down)
        float lookY = lookInput.y * sensitivity;

        // Gamepad values are usually -1..1 and should be scaled by deltaTime.
        // Mouse values are already "delta" and typically should NOT be scaled by deltaTime.
        if (usingGamepad)
        {
            yaw *= Time.deltaTime;
            lookY *= Time.deltaTime;
        }

        // Apply pitch (invert by subtracting so mouse up looks up)
        pitch -= lookY;

        // Clamp pitch so you can't flip the camera upside down
        pitch = Mathf.Clamp(pitch, -89f, 89f);

        // Apply pitch to the camera only
        playerCamera.transform.localRotation = Quaternion.Euler(pitch, 0f, 0f);

        // Apply yaw to the player body
        transform.Rotate(Vector3.up * yaw);
    }

    #endregion

    #region Debug Visualization (Gizmos)

    void OnDrawGizmos()
    {
        // Only draw while the game is running, and only if we have a camera reference
        if (!Application.isPlaying || playerCamera == null)
        {
            return;
        }

        // Set gizmo color
        Gizmos.color = Color.red;

        // Draw the interaction ray in the scene view
        Ray ray = playerCamera.ViewportPointToRay(new Vector3(0.5f, 0.5f, 0f));
        Gizmos.DrawLine(ray.origin, ray.origin + ray.direction * interactDistance);
    }

    #endregion
}
